name: STG Database Migration

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'STGにマイグレーションを適用'
        required: true
        type: string

jobs:
  migrate-staging:
    if: github.event.inputs.confirmation == 'STGにマイグレーションを適用'
    runs-on: ubuntu-latest
    environment: STG
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run migration on staging
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: supabase db push
        
      - name: Output result
        run: echo "✅ STG環境へのマイグレーションが完了しました"