name: Database Migration

on:
  issue_comment:
    types: [created]

jobs:
  migrate-staging:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'stgにマイグレーションを適用')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run migration on staging
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_STG }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_STG }}
        run: supabase db push
        
      - name: Comment result
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ STG環境へのマイグレーションが完了しました'
            })

  migrate-production:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'prodにマイグレーションを適用')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run migration on production
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_PROD }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_PROD }}
        run: supabase db push
        
      - name: Comment result
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ PROD環境へのマイグレーションが完了しました'
            })